name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted   # usa o seu runner stormforge
    steps:
      # 1. Checkout do código
      - uses: actions/checkout@v4

      # 2. Entrar em uma pasta específica no servidor
      - name: Entrar na pasta do projeto
        run: cd /var/banap/ms_producer_banap/ && git pull origin main

      # 3. Instalar dependências
      - name: Instalar dependências
        run: |
          cd /var/banap/ms_producer_banap/
          npm install

      # 4. Declarar variaveis de ambiente
      - name: Variaveis de ambiente
        run: |
          export DB_HOST='stormforge.lan'
          export DB_PORT=5432
          export DB_USER=Green
          export DB_PASSWORD=StormForge01
          export DB_NAME=banap_database
      # 4. Rodar sua aplicação
      - name: Rodar app
        run: |
          cd /var/banap/ms_producer_banap/
          npm run start

      
